apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  namespace: default
  name: pod-exec
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["get", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: default
  name: bind-pod-roles
subjects:
  - kind: ServiceAccount
    name: default
    namespace: default
roleRef:
  kind: ClusterRole
  name: pod-exec
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Service
metadata:
  name: minizinc-app-service
spec:
  selector:
    app: minizinc-app
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minizinc-app
spec:
  selector:
    matchLabels:
      app: minizinc-app
  replicas: 1
  template:
    metadata:
      labels:
        app: minizinc-app
    spec:
      containers:
        - name: minizinc-app
          image: minizinc-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: minizinc-solver-service
spec:
  selector:
    app: minizinc-solver
  ports:
    - protocol: "TCP"
      port: 7000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minizinc-solver
spec:
  selector:
    matchLabels:
      app: minizinc-solver
  replicas: 1
  template:
    metadata:
      labels:
        app: minizinc-solver
    spec:
      containers:
        - name: minizinc-solver
          image: minizinc-solver:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minizinc-cmd
spec:
  selector:
    matchLabels:
      app: minizinc-cmd
  replicas: 1
  template:
    metadata:
      labels:
        app: minizinc-cmd
    spec:
      containers:
        - name: minizinc-cmd
          image: minizinc-cmd:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
