FROM node:14-alpine
ENV NODE_ENV=production

WORKDIR /app

COPY ["package.json", "./"]

RUN npm install

COPY ["./src","./public",".eslintrc.json", "next.config.cjs","tsconfig.json", "prepare.sh", "./"]

ARG API_URL

ENV API_URL ${API_URL}

RUN sh ./prepare.sh

RUN npx next build

EXPOSE 3000
# 
# CMD ["sh", "-c",  "${NEXT_PUBLIC_API_URL}"]

COPY test .

RUN npm install cypress 

RUN npm install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

RUN npx cypress run --config video=false --project ./test