version: '3.7'

services:
  react-frontend-image:
    image: handvask-frontend-image
    build:
      context: .
      dockerfile: Dockerfile
      args:
        API_URL: ${NEXT_PUBLIC_API_URL}
    environment:
      - ARTIFACT_LOCATION_FRONTEND=${ARTIFACT_LOCATION_FRONTEND}
      - COMMIT_SHA=${COMMIT_SHA}
    ports:
      - "3000:3000"