version: '3.7'

services:
  react-frontend-image:
    image: handvask-frontend-image
    build:
      context: ./handvask_frontend
      dockerfile: Dockerfile
      args:
        API_URL: http://localhost:8080/
    ports:
      - "3000:3000"