version = 1

exclude_patterns = ["/frontend/dist/*.min.js"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/Handvask/handvask"

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[transformers]]
name = "dotnet-format"
enabled = true

[[transformers]]
name = "gofumpt"
enabled = true

[[transformers]]
name = "black"
enabled = true

[[transformers]]
name = "isort"
enabled = true