version = 1

exclude_patterns = ["/frontend/dist/*.min.js"]

[[analyzers]]
name = "terraform"
enabled = true

[[analyzers]]
name = "csharp"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]

[[transformers]]
name = "dotnet-format"
enabled = true