steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  [
    'build', 
    '-t',
    'europe-north1-docker.pkg.dev/handvask/handvask-artifacts/python_backend:latest',
    './python_backend'
  ]
- name: 'gcr.io/cloud-builders/docker'
  args:
  [
    'push',
    'europe-north1-docker.pkg.dev/handvask/handvask-artifacts/python_backend:latest'
  ]
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  timeout: 240s
  args: ['compute', 'instances', 
        'create-with-container', 'handvask',
        '--container-image', 
        'europe-north1-docker.pkg.dev/handvask/handvask-artifacts/python_backend:latest']
  env:
    - 'CLOUDSDK_COMPUTE_REGION=europe-north1'
    - 'CLOUDSDK_COMPUTE_ZONE=europe-north1-a'
