steps:
  #step 1
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t",
        "--build-arg",
        "NEXT_PUBLIC_API_URL=$$NEXT_PUBLIC_API_URL",
        "$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME-frontend-artifacts/$_SERVICE_NAME-frontend-image:$COMMIT_SHA",
        "./handvask_frontend",
      ]
    secretEnv: ["NEXT_PUBLIC_API_URL"]
  #step 2
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME-frontend-artifacts/$_SERVICE_NAME-frontend-image:$COMMIT_SHA",
      ]
  #step 3
  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "kubernetes-manifests/"]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=europe-north1"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_SERVICE_NAME-cluster"
  #step 4
  - name: "gcr.io/cloud-builders/kubectl"
    args:
      [
        "set",
        "image",
        "deployment",
        "handvask-frontend",
        "handvask-frontend=$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME-frontend-artifacts/$_SERVICE_NAME-frontend-image:$COMMIT_SHA",
      ]
    env:
      - "CLOUDSDK_COMPUTE_ZONE=$_DEPLOY_REGION"
      - "CLOUDSDK_CONTAINER_CLUSTER=$_SERVICE_NAME-cluster"
  # Step 5
  # - name: "gcr.io/cloud-builders/kubectl"
  #   args:
  #     [
  #       "set",
  #       "image",
  #       "expose",
  #       "deployment",
  #       "frontend-service",
  #     ]
substitutions:
  _SUB_VALUE: python-backend
  # _LABELS: gcb-trigger-id=9723ac3b-95ac-44e2-b4e1-0da4e7dc8453
  # _TRIGGER_ID: 9723ac3b-95ac-44e2-b4e1-0da4e7dc8453
  _GCR_HOSTNAME: europe-north1-docker.pkg.dev
  _PLATFORM: managed
  _SERVICE_NAME: handvask
  _DEPLOY_REGION: europe-north1
availableSecrets:
  secretManager:
    - versionName: projects/383672682031/secrets/NEXT_PUBLIC_API_URL/versions/1
      env: "NEXT_PUBLIC_API_URL"
options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE
