steps:
  # step 0;
  - name: ubuntu
    entrypoint: bash
    args:
      [
        "-c",
        "echo $$NEXT_PUBLIC_API_URL",
      ]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "--build-arg",
        "API_URL=$$NEXT_PUBLIC_API_URL",
        "-t",
        "$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME-frontend-artifacts/$_SERVICE_NAME-frontend-image:$COMMIT_SHA",
        "./handvask_frontend",
      ]
    secretEnv: ["NEXT_PUBLIC_API_URL"]
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "container",
        "run", 
        "-d",
        "--name",
        "handvask-frontend",
        "-p",
        "3000:3000",
        "$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME-frontend-artifacts/$_SERVICE_NAME-frontend-image:$COMMIT_SHA",
        
      ]

availableSecrets:
  secretManager:
    - versionName: projects/383672682031/secrets/NEXT_PUBLIC_API_URL/versions/1
      env: NEXT_PUBLIC_API_URL
options:
  logging: CLOUD_LOGGING_ONLY
  substitutionOption: ALLOW_LOOSE