version: '3'

services:
  python-backend-image:
    image: python-backend-image
    build:
      context: ./python_backend
      dockerfile: Dockerfile.workflowTest
    environment:
      - "DB_HOST=${DB_HOST}"
      - "DB_USER=${DB_USER}"
      - "DB_PASS=${DB_PASS}"
      - "DB_NAME=${DB_NAME}"
      - "HANDVASK_FRONTEND_URL=${HANDVASK_FRONTEND_URL}"
      - "REGION=${ARTIFACT_LOCATION_BACKEND}"
    ports:
      - "8080:8080"