apiVersion: skaffold/v3
kind: Config
metadata:
  name: handvask
build:
  artifacts:
  - image: handvask-frontend-image
    context: handvask_frontend
    docker:
      dockerfile: Dockerfile
  - image: handvask-minizinc-app-image
    context: minizinc/app
    docker:
      dockerfile: Dockerfile
  - image: handvask-minizinc-solver-image
    context: minizinc/solver
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - handvask_frontend/k8s/frontend-deploy.yaml
  - handvask_frontend/k8s/frontend-service.yaml
  - minizinc/k8s/deployment.yaml
