apiVersion: skaffold/v3
kind: Config
metadata:
  name: handvask
build:
  artifacts:
    - image: backend
      context: python_backend
      docker:
        dockerfile: Dockerfile
    - image: frontend
      context: handvask_frontend
      # sync:
      #   manual:
      #     - src: "src/***/*.ts"
      #       dest: "/app/src"
      #     - src: "src/***/*.tsx"
      #       dest: "/app/src"
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - kubernetes-manifests/backend-deploy.yaml
    - kubernetes-manifests/backend-service.yaml
    - kubernetes-manifests/frontend-deploy.yaml
    - kubernetes-manifests/frontend-service.yaml
