apiVersion: apps/v1
kind: Deployment
metadata:
  name: handvask-frontend
spec:
  selector:
    matchLabels:
      app: handvask-frontend
  template:
    metadata:
      labels:
        app: handvask-frontend
    spec:
      containers:
        - name: handvask-frontend
          image: ${ARTIFACT_LOCATION_FRONTEND}:${COMMIT_SHA}
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 300m
              memory: 512Mi
          ports:
            - containerPort: 3000
