kind: Service
apiVersion: v1
metadata:
  name: handvask-frontend-service
spec:
  selector:
    run: handvask-frontend-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
