apiVersion: "v1"
kind: "Service"
metadata:
  name: "handvask-frontend-service"
  namespace: "default"
spec:
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 3000
  selector:
    app: "handvask-frontend"
  type: "LoadBalancer"
  loadBalancerIP: ""
