version: '3'

services:
  python-backend-image:
    image: python-backend-image
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - "DB_HOST=${DB_HOST}"
      - "DB_USER=${DB_USER}"
      - "DB_PASS=${DB_PASS}"
      - "DB_NAME=${DB_NAME}"
      - "HANDVASK_FRONTEND_ORIGIN=${HANDVASK_FRONTEND_ORIGIN}"
      - "REGION=${ARTIFACT_LOCATION_BACKEND}"
      - "MZN_API_KEY=${API_KEY}"
      - "MZN_MN_HOST=${MZN_MN_HOST}"
    ports:
      - "8080:8080"