version: '3.7'



services:
  handvask-minizinc-image:
    image: handvask-minizinc-image
    build:
      context: app/
      dockerfile: Dockerfile
    environment:
      - "API_KEY=${API_KEY}"
      - "BACKEND_HOST=${BACKEND_HOST}"
      - "SOLVER_IMAGE=${SOLVER_IMAGE}"
      - "HOST_URL=${HOST_URL}"
      - "CACERT=${CACERT}"
      - "TOKEN=${TOKEN}"
    ports:
      - 5000:8383

  handvask-minizinc-solver-image:
    image: handvask-minizinc-solver-image
    build:
      context: solver/
      dockerfile: Dockerfile
