apiVersion: skaffold/v3
kind: Config
metadata:
  name: minizinc
build:
  artifacts:
  - image: minizinc-app
    context: app
    docker:
      dockerfile: Dockerfile
  - image: minizinc-solver
    context: solver
    docker:
      dockerfile: Dockerfile
manifests:
  rawYaml:
  - deployment.yaml
