name: Changes in backend, build
on:
  push:
    branches:
      - "backend_testing"
    paths:
      - "python_backend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/383672682031/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
          service_account: "morten-service@handvask.iam.gserviceaccount.com"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
      - name: Build env file
        run: |
          touch ./python_backend/.env
          echo "DB_HOST=${{secrets.DB_HOST}}" >> ./python_backend/.env
          echo "DB_USER=${{secrets.DB_USER}}" >> ./python_backend/.env
          echo "DB_PASS=${{secrets.DB_PASS}}" >> ./python_backend/.env
          echo "DB_NAME=${{secrets.DB_NAME}}" >> ./python_backend/.env
      - name: Build python_backend image.
        run: |
          cd python_backend
          docker build --tag handvask_backend_python:latest -f Dockerfile.backend .
