name: Docker Image CI

on:
  pull_request:
    branches: [ "pipeline_1" ]
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build ./python_backend --file Dockerfile --tag handvask_backend_python:$(date +%s)
