name: Docker python_backend_handvask

on:
  push:
    branches: [ "pipeline_1" ]
    # paths:
    #   - "/python_backend/**"
    #   - "/.github/workflows/docker-image.yml"
  pull_request:
    branches: [ "pipeline_1" ]
    

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      run: |
        touch ./python_backend/.env
        echo "export DB_HOST=${{secrets.DB_HOST}}" >> .env
        echo "export DB_USER=${{secrets.DB_USER}}" >> .env
        echo "export DB_PASS=${{secrets.DB_PASS}}" >> .env
        echo "export DB_NAME=${{secrets.DB_NAME}}" >> .env
    - name: Build python_backend image.
      run: |
        docker build ./python_backend --tag handvask_backend_python:$(date +%s)

