name: Change in frontend, build.
on:
  push:
    branches:
    - "main"
    paths:
    - "handvask_frontend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: "projects/383672682031/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
          service_account: "morten-service@handvask.iam.gserviceaccount.com"
      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
      # - name: Build env file
      #   run: |
      #     touch ./python_backend/.env
      #     echo "export DB_HOST=${{secrets.DB_HOST}}" >> ./python_backend/.env
      #     echo "export DB_USER=${{secrets.DB_USER}}" >> ./python_backend/.env
      #     echo "export DB_PASS=${{secrets.DB_PASS}}" >> ./python_backend/.env
      #     echo "export DB_NAME=${{secrets.DB_NAME}}" >> ./python_backend/.env
      - name: Build frontend docker image.
        run: |
          docker build ./handvask_frontend --tag handvask_frontend_handvask:latest
      - id: "access-secret"
        run: |-
          gcloud auth configure-docker
          docker tag handvask_frontend_handvask:latest eu.gcr.io/handvask/handvask_frontend_handvask:latest
          docker push eu.gcr.io/handvask/handvask_frontend_handvask:latest
