name: "pipeline_1, test file"
on:
  push:
    branches:
      - "pipeline_1"
jobs:
  # frontend-image-build:
  #   needs: Authenticate-GKE
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: "read"
  #     id-token: "write"
  #   steps:

  #     - name: Checkout
  #       uses: actions/checkout@v3
  #     - name: Echo 1
  #       run: |
  #         echo "Hello World, 1"
  #     - name: list gcloud auth, to see if it works
  #       run: |
  #         gcloud auth list
  #     - name: Authenticate to Google Cloud
  #       id: "auth"
  #       uses: google-github-actions/auth@v1
  #       with:
  #         workload_identity_provider: "projects/383672682031/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
  #         service_account: "morten-service@handvask.iam.gserviceaccount.com"
  #     - name: "Configure Docker to use the gcloud command-line tool as a credential helper"
  #       run: |
  #         gcloud \
  #         auth \
  #         configure-docker europe-north1-docker.pkg.dev
  #     - name: Docker-compose build frontend image.
  #       run: |
  #         cd handvask_frontend && \
  #         docker \
  #         compose \
  #         build
  #     - name: Tag DockerImage
  #       run: |
  #         docker \
  #         tag handvask-frontend-image ${{secrets.ARTIFACT_LOCATION_BACKEND}}:${{ github.sha }}
  #     - name: Push DockerImage
  #       run: |
  #         docker push ${{secrets.ARTIFACT_LOCATION_BACKEND}}:${{ github.sha }}
  deploy-to-GKE:
    # needs: frontend-image-build
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Authenticate to Google Cloud
        id: "auth"
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/383672682031/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
          service_account: "morten-service@handvask.iam.gserviceaccount.com"
      - name: set compute region
        run: |
          gcloud \
          config \
          set compute/region europe-north1
      - name: "Configure Docker to use the gcloud command-line tool as a credential helper"
        run: | 
          gcloud \
          container \
          clusters \
          get-credentials handvask-cluster
      - name: kubectl apply for deployment
        run: |
          kubectl \
          apply \
          -f handvask_frontend/k8s/
      - name: Deploy to GKE
        run: |
          kubectl \
          set \
          image handvask-frontend \
          handvask-frontend=${{secrets.ARTIFACT_LOCATION_BACKEND}}:${{ github.sha }}
          kubectl \
          rollout status deployment/handvask-frontend



