name: testing_pipeline

on:
  push:
    paths:
      - "python_backend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Build env file
        uses: SpicyPizza/create-envfile@v.1.3.0
        with:
          envkey_DB_HOST: ${{ secrets.DB_HOST }}
          envkey_DB_USER: ${{ secrets.DB_USER }}
          envkey_DB_PASS: ${{ secrets.DB_PASS }}
          envkey_DB_NAME: ${{ secrets.DB_NAME }}
          directory: ./python_backend
          filename: .env
          fail_on_empty: true
      - name: print env content
        run: |
          cat ./python_backend/.env
      - name: Build python_backend image.
        run: |
          docker build ./python_backend --tag handvask_backend_python:latest
