name: testing-pipeline

on:
  push:
    branches:
      - "pipeline_1"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - name: Build env file
        run: |
          touch ./handvask_frontend/.env
          echo "NEXT_PUBLIC_API_URL=${{secrets.NEXT_PUBLIC_API_URL}}
      - name: Build frontend docker image.
        run: |
          docker build ./handvask_frontend --tag handvask_frontend_handvask:latest
