name: testing-pipeline

on:
  push:
    paths:
      - '.github/workflows/**'
      - "python_backend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Run actions check
        uses: actions/checkout@v3
      - name: Build env file
        run: |
          touch ./python_backend/.env
          echo "export DB_HOST=${{secrets.DB_HOST}}" >> ./python_backend/.env
          echo "export DB_USER=${{secrets.DB_USER}}" >> ./python_backend/.env
          echo "export DB_PASS=${{secrets.DB_PASS}}" >> ./python_backend/.env
          echo "export DB_NAME=${{secrets.DB_NAME}}" >> ./python_backend/.env
      - name: print env content
        run: |
          cat ./python_backend/.env
      - name: Build python_backend image.
        run: |
          docker build ./python_backend --tag handvask_backend_python:latest
