name: "pipeline_1, test file"
on:
  push:
    branches:
      - "pipeline_1"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Echo 1
        run: |
          echo "Hello World, 1"
      # - name: Docker-compose build frontend image.
      #   run: |
      #     cd handvask_frontend && \
      #     docker \
      #     compose \
      #     build
      # - name: Tag DockerImage
      #   run: |
      #     docker \
      #     tag handvask-frontend-image ${{secrets.ARTIFACT_LOCATION_BACKEND}}:${{ github.sha }}
      # - name: Authenticate to Google Cloud
      #   id: "auth"
      #   uses: google-github-actions/auth@v1
      #   with:
      #     workload_identity_provider: "projects/383672682031/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
      #     service_account: "morten-service@handvask.iam.gserviceaccount.com"
      - name: "Configure Docker to use the gcloud command-line tool as a credential helper"
        run: |
          gcloud \
          auth \
          configure-docker europe-north1-docker.pkg.dev
      - name: Push DockerImage
        run: |
          docker push ${{secrets.ARTIFACT_LOCATION_BACKEND}}:${{ github.sha }}
  deploy-to-GKE:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Echo 2
        run: |
          echo "Hello World, 2"
      # - name: Authenticate to Google Cloud
      #   id: "auth"
      #   uses: google-github-actions/auth@v1
      #   with:
      #     workload_identity_provider: "projects/383672682031/locations/global/workloadIdentityPools/my-pool/providers/my-provider"
      #     service_account: "morten-service@handvask.iam.gserviceaccount.com"
    
  


