name: "pipeline_1, test file"
on:
  push:
    branches:
      - "pipeline_1"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run pytest
        run: |
          docker \
          build \
          -t handvask_backend_test \
          -f ./python_backend/Dockerfile.backend \
          ./python_backend
      - name: run pytest
        run: |
          docker \
          run \
          --rm \
          handvask_backend_test
      - name: Build backend image.
        id: "build-image"
        run: |
          docker \
          compose \
          build
        env:
          DB_HOST: "${{secrets.DB_HOST}}"
          DB_USER: "${{secrets.DB_USER}}"
          DB_PASS: "${{secrets.DB_PASS}}"
          DB_NAME: "${{secrets.DB_NAME}}"
          HANDVASK_FRONTEND_ORIGIN: "*"
          ARTIFACT_LOCATION_BACKEND: "${{secrets.ARTIFACT_LOCATION_BACKEND}}"

      #      Work in progress, dont look at it!
      # - name: Curl for a response, to check if deployment succeeded.
      #   id: check
      #   run: |
      #     response = $(curl -i https://handvask-giawyejmea-lz.a.run.app/ | grep -E 'HTTP/(2|3) 200') &&
      #     echo "::set-output name=response::$response"
      # - name: Check if deployment succeeded.
      #   if: ${{ steps.check.outputs.response != 'HTTP/2 200' }} || ${{ steps.check.outputs.response != 'HTTP/3 200' }}
      #   run: |
      #     echo "Deployment failed."
      #     exit 1
