name: testing-pipeline
on:
  push:
    branches:
      - "pipeline_1"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: actions/checkout@v3
      - name: Build backend image.
        run: |
          docker build ./python_backend -t python_backend:${{ github.sha }}
      - name: test
        run: |
          docker run python_backend:${{ github.sha }} python -m pytest