name: Backend Deploy - Serverless
on:
  push:
    branches:
      - "pipeline_1"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      #      Work in progress, dont look at it!
      - name: Curl for a response, to check if deployment succeeded.
        id: check
        run: |
          response = $(curl -i https://handvask-giawyejmea-lz.a.run.app/ | grep -E 'HTTP/(2|3) 200') &&
          echo "::set-output name=response::$response"
      - name: Check if deployment succeeded.
        if: ${{ steps.check.outputs.response != 'HTTP/2 200' }} || ${{ steps.check.outputs.response != 'HTTP/3 200' }}
        run: |
          echo "Deployment failed."
          exit 1
