name: Pull-request main branch
on:
  pull_request:
    branches:
      - "main"
    paths:
      - "python_backend/**"
      - "minizinc/**"
      - "handvask_frontend/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: run pytest
        run: |
          docker \
          build \
          -t handvask_backend_test \
          -f ./python_backend/Dockerfile.backend \
          ./python_backend
        continue-on-error: true
      - name: Build backend image.
        id: "build-image"
        run: |
          docker \
          compose \
          build
        env:
          DB_HOST: "${{secrets.DB_HOST}}"
          DB_USER: "${{secrets.DB_USER}}"
          DB_PASS: "${{secrets.DB_PASS}}"
          DB_NAME: "${{secrets.DB_NAME}}"
          HANDVASK_FRONTEND_ORIGIN: "*"
          ARTIFACT_LOCATION_BACKEND: "${{secrets.ARTIFACT_LOCATION_BACKEND}}"
      - name: Build frontend docker image.
        run: |
          docker build ./handvask_frontend --tag handvask_frontend_handvask:latest
