name: Docker python_backend_handvask

on:
  # push:
  #   branches: ["main"]
  pull_request:
    branches: 
    - "main"
    paths:
      - "python_backend/**"
      - ".github/workflows/pull_request_main_branch.yml"
      - "minizinc/**"
      - "handvask_frontend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build env file
        run: |
          touch ./python_backend/.env
          echo "DB_HOST=${{secrets.DB_HOST}}" >> ./python_backend/.env
          echo "DB_USER=${{secrets.DB_USER}}" >> ./python_backend/.env
          echo "DB_PASS=${{secrets.DB_PASS}}" >> ./python_backend/.env
          echo "DB_NAME=${{secrets.DB_NAME}}" >> ./python_backend/.env
      - name: Build python_backend image.
        run: |
          docker build ./python_backend --tag handvask_backend_python:latest
      - name: Build frontend docker image.
        run: |
          docker build ./handvask_frontend --tag handvask_frontend_handvask:latest
